export const productList = [
    {
        title: "Face Foam Wash",
        category: "Face & Lip Care",
        originalPrice: 3500.0,
        discountedPrice: null,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545821/HNG/gj685wqvpkzowzlrj5gk.jpg",
        imageAlt: "Face Foam Wash",
        new: true,
        description: "Gentle cleansing foam that removes impurities and makeup.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: null,
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Lip Balm",
        category: "Face & Lip Care",
        originalPrice: 1200.0,
        discountedPrice: 850.0,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545812/HNG/l8k9pwofiykawnm2odll.jpg",
        imageAlt: "Lip Balm",
        new: false,
        description: "Moisturizing lip balm with a hint of color.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: (((1200 - 850) / 1200) * 100).toFixed(0),
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Anti-Aging Cream",
        category: "Face & Lip Care",
        originalPrice: 5000.0,
        discountedPrice: null,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545817/HNG/p0yj5wtmszv1gksqwjwv.jpg",
        imageAlt: "Anti-Aging Cream",
        new: true,
        description: "Reduces the appearance of fine lines and wrinkles.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: null,
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Hydrating Serum",
        category: "Face & Lip Care",
        originalPrice: 4200.0,
        discountedPrice: null,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545816/HNG/zrstib9phue6efb1ej3j.jpg",
        imageAlt: "Hydrating Serum",
        new: true,
        description: "Boosts skin hydration for a radiant glow.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: null,
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Sunscreen Lotion",
        category: "Face & Lip Care",
        originalPrice: 2800.0,
        discountedPrice: 2100.0,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545815/HNG/emiaxo2ietlq0b5wfb62.jpg",
        imageAlt: "Sunscreen Lotion",
        new: false,
        description: "Broad-spectrum SPF 50 protection.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: (((2800 - 2100) / 2800) * 100).toFixed(0),
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Exfoliating Scrub",
        category: "Face & Lip Care",
        originalPrice: 3200.0,
        discountedPrice: null,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545813/HNG/feyfp0jbw63fz471as3d.jpg",
        imageAlt: "Exfoliating Scrub",
        new: true,
        description: "Gently exfoliates to reveal smoother skin.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: null,
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Nourishing Night Cream",
        category: "Face & Lip Care",
        originalPrice: 4500.0,
        discountedPrice: 3375.0,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545812/HNG/skn9bnbswjxrjpi0cor5.jpg",
        imageAlt: "Nourishing Night Cream",
        new: false,
        description: "Deeply nourishes and repairs skin overnight.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: (((4500 - 3375) / 4500) * 100).toFixed(0),
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Eye Gel",
        category: "Face & Lip Care",
        originalPrice: 3000.0,
        discountedPrice: null,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545808/HNG/wbhdsn152ohhkbonlu2w.jpg",
        imageAlt: "Eye Gel",
        new: true,
        description: "Reduces puffiness and dark circles.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: null,
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Vitamin C Serum",
        category: "Face & Lip Care",
        originalPrice: 5500.0,
        discountedPrice: 4125.0,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545807/HNG/neqkib19bamod0ws6gpf.jpg",
        imageAlt: "Vitamin C Serum",
        new: false,
        description: "Brightens skin and evens out skin tone.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: (((5500 - 4125) / 5500) * 100).toFixed(0),
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Face Mask",
        category: "Face & Lip Care",
        originalPrice: 2500.0,
        discountedPrice: null,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545795/HNG/aihda4uennnfj5nwvttd.jpg",
        imageAlt: "Face Mask",
        new: true,
        description: "Revitalizing face mask for all skin types.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: null,
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Acne Treatment",
        category: "Face & Lip Care",
        originalPrice: 3800.0,
        discountedPrice: 2850.0,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545804/HNG/k56tts2yptds6sz0ccep.jpg",
        imageAlt: "Acne Treatment",
        new: false,
        description: "Effective solution for acne-prone skin.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: (((3800 - 2850) / 3800) * 100).toFixed(0),
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Lip Scrub",
        category: "Face & Lip Care",
        originalPrice: 1500.0,
        discountedPrice: null,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545809/HNG/q8kwbnaydx4dlb0fobvt.jpg",
        imageAlt: "Lip Scrub",
        new: true,
        description: "Exfoliates and softens lips.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: null,
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Face Toner",
        category: "Face & Lip Care",
        originalPrice: 2300.0,
        discountedPrice: 1725.0,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545798/HNG/o0q0etfythu7oaudyf5j.jpg",
        imageAlt: "Face Toner",
        new: false,
        description: "Balances skin's pH and tightens pores.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: (((2300 - 1725) / 2300) * 100).toFixed(0),
        isInStock: Math.random() >= 0.5,
    },
    {
        title: "Moisturizing Lotion",
        category: "Face & Lip Care",
        originalPrice: 3000.0,
        discountedPrice: null,
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720545799/HNG/hsn9paff6iyxyviis7gh.jpg",
        imageAlt: "Moisturizing Lotion",
        new: true,
        description: "Lightweight lotion for daily hydration.",
        quantity: Math.floor(Math.random() * 51),
        discountPercentage: null,
        isInStock: Math.random() >= 0.5,
    },
];
