export const productList = [
    {
        title: "Face Foam Wash",
        category: "Face & Lip Care",
        originalPrice: "3,500.00",
        discountedPrice: "2,450.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Face Foam Wash",
        new: true,
        description: "Gentle cleansing foam that removes impurities and makeup.",
    },
    {
        title: "Lip Balm",
        category: "Face & Lip Care",
        originalPrice: "1,200.00",
        discountedPrice: "850.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Lip Balm",
        new: false,
        description: "Moisturizing lip balm with a hint of color.",
    },
    {
        title: "Anti-Aging Cream",
        category: "Face & Lip Care",
        originalPrice: "5,000.00",
        discountedPrice: "3,750.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Anti-Aging Cream",
        new: true,
        description: "Reduces the appearance of fine lines and wrinkles.",
    },
    {
        title: "Hydrating Serum",
        category: "Face & Lip Care",
        originalPrice: "4,200.00",
        discountedPrice: "3,150.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Hydrating Serum",
        new: true,
        description: "Boosts skin hydration for a radiant glow.",
    },
    {
        title: "Sunscreen Lotion",
        category: "Face & Lip Care",
        originalPrice: "2,800.00",
        discountedPrice: "2,100.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Sunscreen Lotion",
        new: false,
        description: "Broad-spectrum SPF 50 protection.",
    },
    {
        title: "Exfoliating Scrub",
        category: "Face & Lip Care",
        originalPrice: "3,200.00",
        discountedPrice: "2,400.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Exfoliating Scrub",
        new: true,
        description: "Gently exfoliates to reveal smoother skin.",
    },
    {
        title: "Nourishing Night Cream",
        category: "Face & Lip Care",
        originalPrice: "4,500.00",
        discountedPrice: "3,375.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Nourishing Night Cream",
        new: false,
        description: "Deeply nourishes and repairs skin overnight.",
    },
    {
        title: "Eye Gel",
        category: "Face & Lip Care",
        originalPrice: "3,000.00",
        discountedPrice: "2,250.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Eye Gel",
        new: true,
        description: "Reduces puffiness and dark circles.",
    },
    {
        title: "Vitamin C Serum",
        category: "Face & Lip Care",
        originalPrice: "5,500.00",
        discountedPrice: "4,125.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        new: false,
        description: "Brightens skin and evens out skin tone.",
    },
    {
        title: "Face Mask",
        category: "Face & Lip Care",
        originalPrice: "2,500.00",
        discountedPrice: "1,875.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Face Mask",
        new: true,
        description: "Revitalizing face mask for all skin types.",
    },
    {
        title: "Acne Treatment",
        category: "Face & Lip Care",
        originalPrice: "3,800.00",
        discountedPrice: "2,850.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Acne Treatment",
        new: false,
        description: "Effective solution for acne-prone skin.",
    },
    {
        title: "Lip Scrub",
        category: "Face & Lip Care",
        originalPrice: "1,500.00",
        discountedPrice: "1,125.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Lip Scrub",
        new: true,
        description: "Exfoliates and softens lips.",
    },
    {
        title: "Face Toner",
        category: "Face & Lip Care",
        originalPrice: "2,300.00",
        discountedPrice: "1,725.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Face Toner",
        new: false,
        description: "Balances skin's pH and tightens pores.",
    },
    {
        title: "Moisturizing Lotion",
        category: "Face & Lip Care",
        originalPrice: "3,000.00",
        discountedPrice: "2,250.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Moisturizing Lotion",
        new: true,
        description: "Provides long-lasting moisture.",
    },
    {
        title: "Brightening Cream",
        category: "Face & Lip Care",
        originalPrice: "4,000.00",
        discountedPrice: "3,000.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Brightening Cream",
        new: false,
        description: "Enhances skin's natural radiance.",
    },
    {
        title: "Lip Gloss",
        category: "Face & Lip Care",
        originalPrice: "1,800.00",
        discountedPrice: "1,350.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Lip Gloss",
        new: true,
        description: "Glossy finish with nourishing ingredients.",
    },
    {
        title: "Face Cleanser",
        category: "Face & Lip Care",
        originalPrice: "2,700.00",
        discountedPrice: "2,025.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Face Cleanser",
        new: false,
        description: "Gentle cleanser for daily use.",
    },
    {
        title: "Lip Plumper",
        category: "Face & Lip Care",
        originalPrice: "2,200.00",
        discountedPrice: "1,650.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Lip Plumper",
        new: true,
        description: "Adds volume and hydration to lips.",
    },
    {
        title: "Night Serum",
        category: "Face & Lip Care",
        originalPrice: "4,800.00",
        discountedPrice: "3,600.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "Night Serum",
        new: false,
        description: "Works overnight to rejuvenate skin.",
    },
    {
        title: "BB Cream",
        category: "Face & Lip Care",
        originalPrice: "3,300.00",
        discountedPrice: "2,475.00",
        imageUrl: "https://res.cloudinary.com/kingsleysolomon/image/upload/v1720360327/HNG/y7iri9ujt00i1wjt1u6j.png",
        imageAlt: "BB Cream",
        new: true,
        description: "Light coverage with skincare benefits.",
    },
];
